# Generated by Django 4.0.8 on 2022-11-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djappsebm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
